### PR TITLE
Add exwm-client-message-functions

### PR DESCRIPTION
**Pull request by progfolio**
* exwm.el (exwm-client-message-functions): Abnormal hook for dispatching client messages.
(exwm--on-ClientMessage): delegate to said hook, decompose body into separate hook functions

See: https://github.com/ch11ng/exwm/issues/931

### CODE REVIEW

**Comment by Stebalien** [comment]
I'm not a fan of exposing such a hook to users as EXWM is likely to misbehave if a user mishandles these messages. If the user _really_ needs full control, they can listen to the event themselves and/or advise the function.

In terms of a handling fullscreen changes, etc., I'd add a separate hook for that (like the floating hook, manage hook, etc.).

I _am_ a fan of breaking this up but I wouldn't use a hook. I'd eitehr:

1. Use an internal alist/hash.
2. Use a cond/pcase, explicitly invoking the handler functions.

From my brief look, it appears that we _always_ switch on the "type".

**Comment by progfolio** [comment]
> I'm not a fan of exposing such a hook to users as EXWM is likely to misbehave if a user mishandles these messages. If the user _really_ needs full control, they can listen to the event themselves and/or advise the function.

Isn't that the case for every hook in Emacs?
Of course it can be misused, but it's not the responsibility of package maintainers to support homespun hook functions, so I don't see any more of a burden than the usual hook introduces, and it gives those who wish to change things a way to do it without resorting to advice.

**Comment by Stebalien** [comment]
> Isn't that the case for every hook in Emacs?

Not really. Hooks are user-facing extension points and package authors tend to take care to make sure:

1. They aren't _too_ sharp.
2. They aren't compatibility hazards. A hook is a promise not to change something (without good reason).

I agree we should _have_ a hook, but it should be higher level. Let the user hook into a specific behavior (EXWM is making a window full-screen) instead of asking the user to hook into the raw X event stream.

**Comment by progfolio** [comment]
> 1. They aren't _too_ sharp.

I think any hook can be "too sharp" given that it executes arbitrary code, so it's not a metric I would use to consider whether a hook is worth it or not. All hooks are "caveat utilitor". That's the price of the flexibility.

> 2. They aren't compatibility hazards. A hook is a promise not to change something (without good reason).

Do you foresee any compatibility hazards in this case?
I don't think the X client message format will be changing drastically any time soon.

**Comment by Stebalien** [comment]
In this case, there are multiple ways to get a full screen window:

1. The window can request it.
2. The user can request it.
3. Possibly more in the future.

When we encourage users to hook into low-level features, any low-level change can break their code. That's not to say that we should _prevent_ users from hooking into these features, but we shouldn't encourage it by creating hooks.

If the user _wants_ to receive client messages, they can listen for them the same way EXWM does. But by hooking into EXWM's event stream (and possibly filtering it), they can easily end up getting EXWM into an inconsistent state. Again, we shouldn't _prevent_ this, but this kind of low-level interception is _exactly_ what advice is designed for.

**Comment by progfolio** [comment]
> In this case, there are multiple ways to get a full screen window:
> 
> 1. The window can request it.
> 2. The user can request it.
> 3. Possibly more in the future.
> 
> When we encourage users to hook into low-level features, any low-level change
> can break their code. That's not to say that we should _prevent_ users from
> hooking into these features, but we shouldn't encourage it by creating hooks.
> 
> If the user _wants_ to receive client messages, they can listen for them the
> same way EXWM does. But by hooking into EXWM's event stream (and possibly
> filtering it), they can easily end up getting EXWM into an inconsistent state.
> Again, we shouldn't _prevent_ this, but this kind of low-level interception is
> _exactly_ what advice is designed for.

We'll have to agree to disagree here.
I'm not a fan of when packages eschew hooks in favor of recommending users advise lower level, private package functions. It's not any easier or safer for the users or anyone who wishes to write a compatible library to interact with the library. As often mentioned, advice is the "sledgehammer of last resort".

In any case I've amended the patch to use what I think is a fair compromise.
`exwm--client-message-functions` is now a "private" alist mapping event types to their respective handlers.
The handler, if found, is called with the ID and DATA slots bound in `exwm--on-ClientMessage`.

**Comment by minad** [comment]
> We'll have to agree to disagree here.
I'm not a fan of when packages eschew hooks in favor of recommending users advise lower level, private package functions. It's not any easier or safer for the users or anyone who wishes to write a compatible library to interact with the library. As often mentioned, advice is the "sledgehammer of last resort".

Well, but the client message handling is already *low level*, so you are providing a hook for something which shouldn't really be exposed. I tend to agree that hooks should be provided for high level functionality. Also I am on board with refactoring and decompose the client message handler function.

**Comment by minad** [comment]
> In any case I've amended the patch to use what I think is a fair compromise.
exwm--client-message-functions is now a "private" alist mapping event types to their respective handlers.
The handler, if found, is called with the ID and DATA slots bound in exwm--on-ClientMessage.

This sounds like a good compromise. There also shouldn't be a significant performance impact, given that alist-get/assq is fast for short lists.

**Comment by Stebalien** [comment]
I agree, this sounds like a good compromise.

**Review by Stebalien — APPROVED** [review]

**Comment by Stebalien** [comment]
Tested locally and this appears to work. I'll merge when you mark it ready.

**Comment by progfolio** [comment]
> Tested locally and this appears to work. I'll merge when you mark it ready.

Do not merge yet.
It actually doesn't work.

**Comment by Stebalien** [comment]
Huh. You're right. And yet EXWM sitll... mostly seems to work. I expected it to completely break in this case...

**Comment by Stebalien** [comment]
It looks like we need to set it after starting EXWM (or, even better, have a template with the atom symbols that we then evaluate on init to create the runtime mapping).

TBH, these atoms should probably be properties of the connection itself...

**Comment by progfolio** [comment]
> It looks like we need to set it after starting EXWM (or, even better, have a
> template with the atom symbols that we then evaluate on init to create the
> runtime mapping).
> 
> TBH, these atoms should probably be properties of the connection itself...

I went with a simple approach for now.
Variable is declared, then `setq`'d during `exwm-init`.
Working on my end now.

**Comment by progfolio** [comment]
> But by hooking into EXWM's event stream (and possibly filtering it), they can easily end up getting EXWM into an inconsistent state

> Huh. You're right. And yet EXWM sitll... mostly seems to work. I expected it to completely break in this case...

Looks like it's not as big a threat as it seemed.
I still think a hook might be a good addition if someone requests it, but we can always add that if the need arises.

**Comment by Stebalien** [comment]
Ok, tested minimize, full screen, and close by client request.

**Pull request merged**
