### PR TITLE
Add global minor modes for EXWM's features

### PR DESCRIPTION
**Pull request by Stebalien**
(fixup commits before merging)

### CODE REVIEW

**Comment by Stebalien** [comment]
This applies the feedback from https://github.com/emacs-exwm/exwm/pull/43.

Unfortunately, the autoloads aren't quite correct for minor modes and I'm not sure if there's a way to fix them while still using macros. Specifically, the autoloads should look something like:

```elisp
(defvar exwm-systemtray-mode nil "....")
(custom-autoload exwm-systemtray-mode "exwm-systemtray" nil)
(autoload 'exwm-systemtray-mode "exwm-systemtray" "..." t)
```

Importantly, we're missing the `custom-autoload` which lets one enable minor-modes via the customize system.

**Comment by minad** [comment]
> Unfortunately, the autoloads aren't quite correct for minor modes and I'm not sure if there's a way to fix them while still using macros. Specifically, the autoloads should look something like:

Maybe a better alternative would be to not use a macro for the whole mode, but only for the body `exwm--minor-mode-body`? It could also be a function taking a symbol argument. We cannot automatically define the obsolete function then, but we side step the autoload problem.

**Comment by progfolio** [comment]
> This applies the feedback from #43.
> 
> Unfortunately, the autoloads aren't quite correct for minor modes and I'm not sure if there's a way to fix them while still using macros. Specifically, the autoloads should look something like:
> 
> ```emacs-lisp
> (defvar exwm-systemtray-mode nil "....")
> (custom-autoload exwm-systemtray-mode "exwm-systemtray" nil)
> (autoload 'exwm-systemtray-mode "exwm-systemtray" "..." t)
> ```
> 
> Importantly, we're missing the `custom-autoload` which lets one enable minor-modes via the customize system.

Anything after the autoload-cookie will be copied verbatim to the generated autoloads file.
e.g.

```emacs-lisp
;;;###autoload(defvar exwm-xsettings-mode nil)
;;;###autoload(custom-autoload 'exwm-xsettings-mode "exwm-xsettings" nil)
;;;###autoload(autoload 'exwm-xsettings-mode "exwm-xsettings"
;;;###autoload"Global minormode for toggling EXM Xsettings support.")
(exwm--define-global-minor-mode xsettings
  "Global minor mode for toggling EXWM Xsettings support.")
```

**Comment by progfolio** [comment]
@Stebalien  see #46

**Comment by minad** [comment]
Merged #46

**Pull request closed without merging**
