### PR TITLE
Simplify and improve focus handling (v2)

### PR DESCRIPTION
**Pull request by Stebalien**
Combine both focus update timers into one and ignore windows in "no focus" frames.

This is a simplification of #5 that focuses entirely on combining the two timers. It should be functionally identical to the current code except that it won't focus windows in "no-accept-focus" frames.

In terms of timers:

- Previously, we'd poll the lock with a 0-delay timer, then schedule a deferred focus update.
- Now, we just schedule a deferred focus update without checking the lock, but re-schedule a deferred focus update if we try to commit and find that the lock is set.

### CODE REVIEW

**Comment by minad** [comment]
medranocalvo ***@***.***> writes:

> As a curiosity, is no-accept-focus related to child-frames? Do they now work with
> EXWM?

From my experience, child frames work well with EXWM. For example my
Corfu package uses a child frame to display its completion popup. There
is a problem however if child frames (which are tied to the Emacs frame)
overlap with another X window (an EXWM buffer). Then the X window will
be drawn on top of the child frame, since the X window is located in
front of Emacs. This can be worked around by unparenting the child
frame. I've recently added such a work around to Corfu. Maybe this
answers your question?

**Comment by Stebalien** [comment]
> As a curiosity, is no-accept-focus related to child-frames? Do they now work with EXWM?

I added that for a reason... but didn't write down why. I think it had to do with posframe?

**Comment by Stebalien** [comment]
> I was thinking on some ticket in EXWM about postframe not working.

The issues there are _mostly_ with respect to parent/child frames.

Personally, I fix that with:

```elisp
;; There's an "xwininfo" version of this, but I prefer not to shell out when I can just get the
;; information I need from emacs.
(defun posframe-refposhandler-geometry (&optional frame)
  "Get the upper-left-hand corner of the window without relying on xwininfo."
  (let ((geo (frame-monitor-geometry frame)))
    (cons (nth 0 geo) (nth 1 geo))))

;; I really wish there were a setting somewhere (and should probably upstream one at some point).
(define-advice posframe-show (:around (fn &rest args) defaults)
  (apply fn (append args (list :refposhandler 'posframe-refposhandler-geometry))))
```

**Comment by Stebalien** [comment]
>  Could I have been more explicit (honest question)?

Ah, sorry. I usually look for an explicit "approve". "I think this is the right way to do it" and "I have given this a review and believe it works" aren't always the same thing.

**Pull request merged**
